stages:
- name: 第一阶段
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test-image
      registry: 127.0.0.1:34382
  when:
    event: {}
timeout: 60
notification: {}
