stages:
- name: 发布应用
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    event:
      include:
      - tag
- name: 发布镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker-registry.p-xmb5d-pipeline/test-image:latest
      registry: 127.0.0.1:34382
timeout: 60
notification: {}
