stages:
- name: 第一阶段
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    event: {}
timeout: 60
notification: {}
