apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pod
  template:
    metadata: 
      labels:
        app: test-pod
    spec:
      containers:
      - image: docker-registry.p-xmb5d-pipeline/test-image:latest
        imagePullPolicy: Always
        name: test-deploy-pod
        tty: true
